function fileNullEnsembleResults = GiveMeEnsembleEnrichmentOutputFileName(params)

% Need to find precomputed null results (from running ComputeAllCategoryNulls):
fileNullEnsembleResults = sprintf('PhenotypeNulls_%u_%s-%s_%s_%s_%s.mat',...
                params.e.numNullSamples,params.humanOrMouse,...
                params.structFilter,params.e.whatEnsemble,...
                params.e.whatCorr,params.e.aggregateHow);

end
